version: '3.8'

services:
  crewd:
    build: ./Crewd
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:3000
      - VITE_WS_URL=ws://api:3000
    depends_on:
      - api
    volumes:
      - ./Crewd:/app
      - /app/node_modules

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/discord-clone
      - JWT_SECRET=tu_secreto_jwt_aqui
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
